apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}-nodemanager
  labels:
    app.kubernetes.io/name: {{ include "hdfs.name" . }}
    app.kubernetes.io/component: nodemanager
    {{- include "hdfs.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8088
      name: web
    - port: 8082
      name: web2
    - port: 8042
      name: api
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "hdfs.name" . }}
    app.kubernetes.io/component: nodemanager
    app.kubernetes.io/instance: {{ .Release.Name }}
