apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-namenode
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/hadoop-configmap.yaml") . | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: namenode
    {{- include "hadoop.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hadoop.name" . }}
      app.kubernetes.io/component: namenode
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ include "hadoop.fullname" . }}-namenode
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hadoop.name" . }}
        app.kubernetes.io/component: namenode
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: {{ include "hadoop.name" . }}
                app.kubernetes.io/component: namenode
                {{- include "hadoop.labels" . | nindent 16 }}
        {{- else if eq .Values.antiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "hadoop.name" . }}
                  app.kubernetes.io/component: namenode
                  {{- include "hadoop.labels" . | nindent 18 }}
        {{- end }}
#      initContainers:
#      - name: "chown"
#        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
#        command:
#        - /bin/bash
#        - -c
#        - chown -R hdfs:hadoop /data/dfs &&
#          chmod g+s /data/dfs
#        securityContext:
#          runAsUser: 0
#        volumeMounts:
#        - mountPath: /data/dfs
#          name: dfs
      containers:
      - name: namenode
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
        - "/bin/bash"
        - "/tmp/hadoop-config/bootstrap.sh"
        - "-d"
        - "namenode"
        resources:
{{ toYaml .Values.nameNode.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.nameNode.httpPort }}
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.nameNode.httpPort }}
          initialDelaySeconds: 10
          timeoutSeconds: 2
        volumeMounts:
        - name: hadoop-config
          mountPath: /tmp/hadoop-config
        - name: dfs
          mountPath: /data/dfs
      {{- if .Values.prometheus.exporter.enabled }}
      - name: namenode-exporter
        image: "{{ .Values.prometheus.exporter.image }}"
        command:
        - /bin/sh
        - -c
        - java $JAVA_OPTS -jar /opt/fsimage-exporter/fsimage-exporter.jar 0.0.0.0 {{ .Values.prometheus.exporter.port | quote }} /exporter/config-exporter.yml
        ports:
        - containerPort: {{ .Values.prometheus.exporter.port }}
        resources:
          {{ toYaml .Values.prometheus.exporter.resources | indent 10 }}
        volumeMounts:
        - name: hadoop-config
          mountPath: /tmp/hadoop-config
        - name: config-exporter
          mountPath: /exporter
        - name: dfs
          mountPath: /data/dfs
      {{- end }}
      volumes:
      - name: hadoop-config
        configMap:
          name: {{ include "hadoop.fullname" . }}-hadoop
      {{- if .Values.prometheus.exporter.enabled }}
      - name: config-exporter
        configMap:
          name: {{ include "hadoop.fullname" . }}-namenode-exporter
      {{- end }}
      {{- if not .Values.persistence.nameNode.enabled }}
      - name: dfs
        emptyDir: {}
      {{- end }}
  {{- if .Values.persistence.nameNode.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: dfs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "{{ .Values.persistence.nameNode.size }}"
      {{- if .Values.persistence.nameNode.storageClass }}
      {{- if (eq "-" .Values.persistence.nameNode.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.persistence.nameNode.storageClass }}"
      {{- end }}
      {{- end }}
  {{- end }}
